language: node_js

sudo: required
addons:
  chrome: stable

node_js:
  - '8'

git:
  depth: 3

branches:
  only:
    - master

install:
  - npm install

script:
  - npm run test-once
  - npm run build

cache:
  npm: true
  directories:
    - ./node_modules/

before_deploy:
  - cd dist/packages

deploy:
  provider: npm
  email: 369749456@qq.com
  api_key:
    secure: Mkpm1ntHd4gPoU2gF5V4wi6FkjtBffTmNxIvIu7RVVyHUPAs889UohdVkwVgZ5QW0AEkQRur1FgQ+rEZ2YAx7+JEpC/wN+03wuFuWBBtrkF4o6FKzARzlkBa8tf361qf6mDFoqsfmWxcJOWXoDSSbBHVDhPnf5bDVhjuItcfQRxCmA0bGzUCxaoMyPf8el1M63Xms4//7EhUaf77LLrmCGSlRolmQhd1yg7wSeTZt0pGlDCvLtXgb9G2O4Pzlz1R9A3zs7iZ/3j6Oe0y6q4nII+95U9B13iWGCdUza+F0WOm+pWPgEITo08x5KcNX6xcjgS5jzD+3GJELvoNvRTQsQbx5zR+4xchk9ZusMTEJ8jHxvhHNtw9KPODBr7OcuZ2EoFxKn/FUZL1plUHe3cvqg6vdrPWLVlg1KFr8RtNXfgvZs3S43eR8st/gZau7mLYjT9eczwAcBvt1463L1MaNzu2WQsJJOWIRvRBcXfOktUiuLOrxO/dR3kAHKYjRNzvsQqU9ftX236sgPm+/mDS/b+XypqiQwjoLNgRop8auHEzOD4EcxfjZSz7M/bPDJtHX0rN3e3TQT7ofJyWDrSqshPQWmnGGQEjwWEobdwjHl3B6nxWg+LsrhqK1FaT//IzhX0nFWA7UIGvFCjFiW3hI8Oqdlx2XekfuIiGxbosMlI=
    skip_cleanup: true
  on:
    branches:
      - master
      - /^v\d+(\.\d+)+$/
